# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 77dc503f84d9f83113d95e11d7ca8b66aac3341a36fcced4842fe3e34d5669faef2c0eb72b95c84362395326d7b4046616d4d4aa0fa1b4394fc75256b0fe09d3

test:
  secret_key_base: e12021d7d902252137c3aa974b65c70ac41850cea57b9f0cbb8807644f76c96d8c7c6908fe4a7e0951d6fb070f387dbf49771406e962cf259e6888b280451594

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
